# Generated by Django 4.0.5 on 2022-10-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_sponspored_event_sponsored_book_upload_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='orcid',
        ),
        migrations.AlterField(
            model_name='book',
            name='digital_obj_id',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='indexing',
            field=models.CharField(choices=[('SCI', 'SCI'), ('SCIE', 'SCIE'), ('SCOPUS', 'SCOPUS'), ('Springer', 'Springer'), ('Ei Compendex', 'Ei Compendex'), ('Others', 'Others')], max_length=20),
        ),
        migrations.AlterField(
            model_name='conference',
            name='article_title',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='conference',
            name='digital_obj_id',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='article_title',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='journal',
            name='digital_obj_id',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='google_scholar',
            field=models.URLField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='linkedin',
            field=models.URLField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='personal_page',
            field=models.URLField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='research_gate',
            field=models.URLField(blank=True, max_length=350, null=True),
        ),
    ]
