# Generated by Django 4.0.5 on 2022-10-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_book_isbn_remove_personal_orcid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default=' ', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal',
            name='orcid',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
