# Generated by Django 4.0.5 on 2022-12-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_book_isbn_personal_orcid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='journal_name',
            field=models.CharField(max_length=512),
        ),
    ]
