# Generated by Django 4.0.5 on 2022-07-16 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, primary_key=True, serialize=False, unique=True, verbose_name='email')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(to='auth.group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='personal',
            fields=[
                ('Emp_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Designation', models.CharField(max_length=100)),
                ('School', models.CharField(max_length=100)),
                ('DOJ', models.DateField()),
                ('DOB', models.DateField()),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('ORCID_ID', models.IntegerField()),
                ('Researchgate', models.CharField(max_length=100)),
                ('linkedin', models.CharField(max_length=100)),
                ('Google_scholar_name', models.CharField(max_length=100)),
                ('Personal_page', models.CharField(max_length=100)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='patent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patent_title', models.CharField(max_length=40)),
                ('Type_of_patent', models.CharField(choices=[('National', 'National'), ('International', 'International')], max_length=20)),
                ('no_of_authors_in_patent', models.IntegerField()),
                ('Author_pos', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)])),
                ('patent_created_date', models.DateField()),
                ('Emp_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.personal')),
            ],
        ),
        migrations.CreateModel(
            name='journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('no_of_authors', models.IntegerField()),
                ('Designation', models.CharField(max_length=20)),
                ('Collaboration', models.CharField(choices=[('National', 'National'), ('International', 'International'), ('Internal', 'Internal')], max_length=20)),
                ('Author_pos', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)])),
                ('Journal_name', models.CharField(max_length=100)),
                ('Indexing', models.CharField(choices=[('SCI', 'SCI'), ('SCIE', 'SCIE'), ('SCOPUS', 'SCOPUS')], max_length=20)),
                ('Impact_factor', models.FloatField(null=True)),
                ('year', models.IntegerField()),
                ('Vol_no', models.IntegerField(null=True)),
                ('Issue_no', models.IntegerField(null=True)),
                ('DOI', models.CharField(max_length=30, null=True)),
                ('Type_of_publication', models.CharField(choices=[('Open Access', 'Open Access'), ('Subscription', 'Subscription')], max_length=100)),
                ('Funder_name', models.CharField(blank=True, max_length=100, verbose_name='Enter Funder name if type is "Open" ')),
                ('Amount_of_Publication', models.IntegerField(blank=True, null=True, verbose_name='Enter Amount of Publication if type is "Open" ')),
                ('Support', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4, null=True, verbose_name='Whether Support received from Vellore Institute of Technology?')),
                ('Emp_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.personal')),
            ],
        ),
        migrations.CreateModel(
            name='consultancy_project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_consultancy', models.CharField(choices=[('Product development', 'Product development'), ('Research Collaboration', 'Research Collaboration')], max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('Funding', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True)),
                ('Amount', models.IntegerField(blank=True, null=True, verbose_name='if funding recieved Enter Amount:')),
                ('invoice_number', models.IntegerField(blank=True, null=True, verbose_name='if funding recieved Enter invoice')),
                ('consultancy_startdate', models.DateField()),
                ('consultancy_enddate', models.DateField()),
                ('Emp_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.personal')),
            ],
        ),
        migrations.CreateModel(
            name='conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('no_of_authors', models.IntegerField()),
                ('Designation', models.CharField(max_length=20)),
                ('Collaboration', models.CharField(choices=[('National', 'National'), ('International', 'International'), ('Internal', 'Internal')], max_length=20)),
                ('Author_pos', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)])),
                ('Conference_name', models.CharField(max_length=100)),
                ('Conference_startdate', models.DateField()),
                ('Conference_enddate', models.DateField()),
                ('Place_of_conference', models.CharField(max_length=100)),
                ('Type', models.CharField(choices=[('National', 'National'), ('International', 'International')], max_length=20)),
                ('Indexed_Scopus', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4)),
                ('DOI', models.CharField(max_length=30, null=True)),
                ('Type_of_publication', models.CharField(choices=[('Open Access', 'Open Access'), ('Subscription', 'Subscription')], max_length=100)),
                ('Funder_name', models.CharField(blank=True, max_length=100, verbose_name='Enter Funder name if type of publications is "Open" ')),
                ('Amount_of_Publication', models.IntegerField(blank=True, null=True, verbose_name='Enter Amount of Publication if type is "Open" ')),
                ('Support', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4, null=True, verbose_name='Whether Support received from Vellore Institute of Technology?')),
                ('Emp_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.personal')),
            ],
        ),
        migrations.CreateModel(
            name='book_editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('no_of_authors', models.IntegerField()),
                ('Designation', models.CharField(max_length=20)),
                ('Collaboration', models.CharField(choices=[('National', 'National'), ('International', 'International'), ('Internal', 'Internal')], max_length=20)),
                ('Author_pos', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)])),
                ('Indexing', models.CharField(choices=[('SCI', 'SCI'), ('SCIE', 'SCIE'), ('SCOPUS', 'SCOPUS')], max_length=20)),
                ('ISSN_ISBN_number', models.IntegerField()),
                ('year', models.IntegerField()),
                ('publisher_name', models.CharField(max_length=30)),
                ('Type_of_publisher', models.CharField(choices=[('National', 'National'), ('International', 'International')], max_length=30)),
                ('Vol_no', models.IntegerField(null=True)),
                ('Issue_no', models.IntegerField(null=True)),
                ('DOI', models.CharField(max_length=30, null=True)),
                ('Type_of_publication', models.CharField(choices=[('Open Access', 'Open Access'), ('Subscription', 'Subscription')], max_length=100)),
                ('Funder_name', models.CharField(blank=True, max_length=100, verbose_name='Enter if type is "Open" ')),
                ('Amount_of_Publication', models.IntegerField(blank=True, null=True, verbose_name='Enter if type is "Open" ')),
                ('Support', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4, null=True, verbose_name='Whether Support received from Vellore Institute of Technology?')),
                ('Emp_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.personal')),
            ],
        ),
        migrations.CreateModel(
            name='book_chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('no_of_authors', models.IntegerField()),
                ('Designation', models.CharField(max_length=20)),
                ('Collaboration', models.CharField(choices=[('National', 'National'), ('International', 'International'), ('Internal', 'Internal')], max_length=20)),
                ('Author_pos', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)])),
                ('Indexing', models.CharField(choices=[('SCI', 'SCI'), ('SCIE', 'SCIE'), ('SCOPUS', 'SCOPUS')], max_length=20)),
                ('ISSN_ISBN_number', models.IntegerField()),
                ('year', models.IntegerField()),
                ('book_title', models.CharField(max_length=100)),
                ('publisher_name', models.CharField(max_length=30)),
                ('Type_of_publisher', models.CharField(choices=[('National', 'National'), ('International', 'International')], max_length=30)),
                ('Vol_no', models.IntegerField(null=True)),
                ('Issue_no', models.IntegerField(null=True)),
                ('DOI', models.CharField(max_length=30, null=True)),
                ('Type_of_publication', models.CharField(choices=[('Open Access', 'Open Access'), ('Subscription', 'Subscription')], max_length=100)),
                ('Funder_name', models.CharField(blank=True, max_length=100, verbose_name='Enter Funder name if type is "Open" ')),
                ('Amount_of_Publication', models.IntegerField(blank=True, null=True, verbose_name='Enter Amount of Publication if type is "Open" ')),
                ('Support', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4, null=True, verbose_name='Whether Support received from Vellore Institute of Technology?')),
                ('Emp_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.personal')),
            ],
        ),
        migrations.AddConstraint(
            model_name='patent',
            constraint=models.UniqueConstraint(fields=('Emp_ID', 'patent_title'), name='unique_EmpID_PTitle_combination'),
        ),
        migrations.AddConstraint(
            model_name='journal',
            constraint=models.UniqueConstraint(fields=('Emp_ID', 'title'), name='unique_EmpID_title_journal'),
        ),
        migrations.AddConstraint(
            model_name='consultancy_project',
            constraint=models.UniqueConstraint(fields=('Emp_ID', 'company_name'), name='unique_EmpID_CName_combination'),
        ),
        migrations.AddConstraint(
            model_name='conference',
            constraint=models.UniqueConstraint(fields=('Emp_ID', 'title'), name='unique_EmpID_title_conference'),
        ),
        migrations.AddConstraint(
            model_name='book_editor',
            constraint=models.UniqueConstraint(fields=('Emp_ID', 'title'), name='unique_EmpID_title_bookEditor'),
        ),
        migrations.AddConstraint(
            model_name='book_chapter',
            constraint=models.UniqueConstraint(fields=('Emp_ID', 'title'), name='unique_EmpID_title_bookChapter'),
        ),
    ]
