# Generated by Django 4.0.5 on 2022-07-01 13:44

import api.models
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='book_chapters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chapter_title', models.CharField(max_length=100)),
                ('no_of_authors', models.IntegerField()),
                ('Author_info', djongo.models.fields.EmbeddedField(model_container=api.models.authorinfo, null=True)),
                ('Author_pos', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)])),
                ('Indexing', models.CharField(choices=[('SCI', 'SCI'), ('SCIE', 'SCIE'), ('SCOPUS', 'SCOPUS')], max_length=20)),
                ('ISSN_ISBN_number', models.IntegerField()),
                ('year', models.IntegerField()),
                ('book_title', models.CharField(max_length=100)),
                ('publisher_name', models.CharField(max_length=30)),
                ('TYpe_of_publisher', models.CharField(choices=[('NationaL', 'NationaL'), ('International', 'International')], max_length=30)),
                ('Vol_no', models.IntegerField(null=True, verbose_name='optional')),
                ('Issue_no', models.IntegerField(null=True, verbose_name='optional')),
                ('DOI', models.CharField(max_length=30, null=True, verbose_name='optional')),
                ('Type_of_publication', models.CharField(choices=[('Open Access', 'Open Access'), ('Subscription', 'Subscription')], max_length=100)),
                ('Funder_name', models.CharField(blank=True, max_length=100, verbose_name='Enter Funder name if type is "Open" ')),
                ('Amount_of_Publication', models.IntegerField(blank=True, null=True, verbose_name='Enter Amount of Publication if type is "Open" ')),
                ('Support', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4, null=True, verbose_name='Whether Support received from Vellore Institute of Technology?')),
            ],
        ),
        migrations.CreateModel(
            name='book_editor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_authors', models.IntegerField()),
                ('Author_info', djongo.models.fields.EmbeddedField(model_container=api.models.authorinfo, null=True)),
                ('Author_pos', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)])),
                ('Indexing', models.CharField(choices=[('SCI', 'SCI'), ('SCIE', 'SCIE'), ('SCOPUS', 'SCOPUS')], max_length=20)),
                ('ISSN_ISBN_number', models.IntegerField()),
                ('year', models.IntegerField()),
                ('book_title', models.CharField(max_length=100)),
                ('publisher_name', models.CharField(max_length=30)),
                ('TYpe_of_publisher', models.CharField(choices=[('NationaL', 'NationaL'), ('International', 'International')], max_length=30)),
                ('Vol_no', models.IntegerField(null=True, verbose_name='optional')),
                ('Issue_no', models.IntegerField(null=True, verbose_name='optional')),
                ('DOI', models.CharField(max_length=30, null=True, verbose_name='optional')),
                ('Type_of_publication', models.CharField(choices=[('Open Access', 'Open Access'), ('Subscription', 'Subscription')], max_length=100)),
                ('Funder_name', models.CharField(blank=True, max_length=100, verbose_name='Enter if type is "Open" ')),
                ('Amount_of_Publication', models.IntegerField(blank=True, null=True, verbose_name='Enter if type is "Open" ')),
                ('Support', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4, null=True, verbose_name='Whether Support received from Vellore Institute of Technology?')),
            ],
        ),
        migrations.CreateModel(
            name='conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Artical_title', models.CharField(max_length=100)),
                ('no_of_authors', models.IntegerField()),
                ('Author_info', djongo.models.fields.EmbeddedField(model_container=api.models.authorinfo, null=True)),
                ('Author_pos', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)])),
                ('Conference_name', models.CharField(max_length=100)),
                ('Conference_startdate', models.DateField()),
                ('Conference_enddate', models.DateField()),
                ('Place_of_conference', models.CharField(max_length=100)),
                ('Type', models.CharField(choices=[('NationaL', 'NationaL'), ('International', 'International')], max_length=20)),
                ('Indexed_Scopus', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4)),
                ('DOI', models.CharField(max_length=30, null=True)),
                ('Type_of_publication', models.CharField(choices=[('Open Access', 'Open Access'), ('Subscription', 'Subscription')], max_length=100)),
                ('Funder_name', models.CharField(blank=True, max_length=100, verbose_name='Enter Funder name if type is "Open" ')),
                ('Amount_of_Publication', models.IntegerField(blank=True, null=True, verbose_name='Enter Amount of Publication if type is "Open" ')),
                ('Support', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4, null=True, verbose_name='Whether Support received from Vellore Institute of Technology?')),
            ],
        ),
        migrations.CreateModel(
            name='consultancy_project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_consultancy', models.CharField(choices=[('Product development', 'Product development'), ('Research Collaboration', 'Research Collaboration')], max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('Funding', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5, null=True)),
                ('Amount', models.IntegerField(blank=True, null=True, verbose_name='if funding recieved Enter Amount:')),
                ('invoice_number', models.IntegerField(blank=True, null=True, verbose_name='if funding recieved Enter invoice')),
                ('Consultancy_startdate', models.DateField()),
                ('Consultancy_enddate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Artical_title', models.CharField(max_length=100)),
                ('no_of_authors', models.IntegerField()),
                ('Author_info', djongo.models.fields.EmbeddedField(model_container=api.models.authorinfo, null=True)),
                ('Author_pos', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)])),
                ('Journal_name', models.CharField(max_length=100)),
                ('Indexing', models.CharField(choices=[('SCI', 'SCI'), ('SCIE', 'SCIE'), ('SCOPUS', 'SCOPUS')], max_length=20)),
                ('Impact_factor', models.FloatField(null=True, verbose_name='optional')),
                ('year', models.IntegerField()),
                ('Vol_no', models.IntegerField(null=True, verbose_name='optional')),
                ('Issue_no', models.IntegerField(null=True, verbose_name='optional')),
                ('DOI', models.CharField(max_length=30, null=True, verbose_name='optional')),
                ('Type_of_publication', models.CharField(choices=[('Open Access', 'Open Access'), ('Subscription', 'Subscription')], max_length=100)),
                ('Funder_name', models.CharField(blank=True, max_length=100, verbose_name='Enter Funder name if type is "Open" ')),
                ('Amount_of_Publication', models.IntegerField(blank=True, null=True, verbose_name='Enter Amount of Publication if type is "Open" ')),
                ('Support', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4, null=True, verbose_name='Whether Support received from Vellore Institute of Technology?')),
            ],
        ),
        migrations.CreateModel(
            name='patent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patent_title', models.CharField(max_length=40)),
                ('Type_of_patent', models.CharField(choices=[('NationaL', 'NationaL'), ('International', 'International')], max_length=20)),
                ('no_of_authors_in_patent', models.IntegerField()),
                ('Author_pos', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)])),
            ],
        ),
        migrations.CreateModel(
            name='personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Designation', models.CharField(max_length=100)),
                ('Emp_ID', models.IntegerField()),
                ('School', models.CharField(max_length=100)),
                ('DOJ', models.DateField()),
                ('DOB', models.DateField()),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('ORCID_ID', models.IntegerField()),
                ('Researchgate', models.CharField(max_length=100)),
                ('linkedin', models.CharField(max_length=100)),
                ('Google_scholar_name', models.CharField(max_length=100)),
                ('Personal_page', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='SampleModel',
        ),
        migrations.AddField(
            model_name='patent',
            name='Emp_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.personal'),
        ),
        migrations.AddField(
            model_name='journal',
            name='Emp_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.personal'),
        ),
        migrations.AddField(
            model_name='consultancy_project',
            name='Emp_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.personal'),
        ),
        migrations.AddField(
            model_name='conference',
            name='Emp_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.personal'),
        ),
        migrations.AddField(
            model_name='book_editor',
            name='Emp_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.personal'),
        ),
        migrations.AddField(
            model_name='book_chapters',
            name='Emp_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.personal'),
        ),
    ]
