# Generated by Django 4.0.5 on 2022-07-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='Google_scholar_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='ORCID_ID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='Personal_page',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='Researchgate',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='linkedin',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
