# Generated by Django 4.0.5 on 2022-08-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_book_editor_emp_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='industrial_interaction',
            name='title',
            field=models.CharField(default='Sample', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher_name',
            field=models.CharField(default='ABC', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='support',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='type',
            field=models.CharField(choices=[('Book Chapter', 'Book Chapter'), ('Book Editorial', 'Book Editorial')], max_length=20),
        ),
    ]
