# Generated by Django 4.0.5 on 2022-07-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_chapter_title_book_chapter_title_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='conference',
            name='unique_EmpID_DOI_combination',
        ),
        migrations.AddConstraint(
            model_name='book_chapter',
            constraint=models.UniqueConstraint(fields=('Emp_ID', 'title'), name='unique_EmpID_title_bookChapter'),
        ),
        migrations.AddConstraint(
            model_name='book_editor',
            constraint=models.UniqueConstraint(fields=('Emp_ID', 'title'), name='unique_EmpID_title_bookEditor'),
        ),
        migrations.AddConstraint(
            model_name='conference',
            constraint=models.UniqueConstraint(fields=('Emp_ID', 'title'), name='unique_EmpID_title_conference'),
        ),
        migrations.AddConstraint(
            model_name='journal',
            constraint=models.UniqueConstraint(fields=('Emp_ID', 'title'), name='unique_EmpID_title_journal'),
        ),
    ]
