# Generated by Django 4.0.5 on 2022-07-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_personal_google_scholar_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='ORCID_ID',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
