# Generated by Django 4.0.5 on 2022-07-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_book_chapter_author_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_chapter',
            name='Collaboration',
            field=models.CharField(choices=[('National', 'National'), ('International', 'International'), ('Internal', 'Internal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='book_chapter',
            name='TYpe_of_publisher',
            field=models.CharField(choices=[('National', 'National'), ('International', 'International')], max_length=30),
        ),
        migrations.AlterField(
            model_name='book_editor',
            name='Collaboration',
            field=models.CharField(choices=[('National', 'National'), ('International', 'International'), ('Internal', 'Internal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='book_editor',
            name='Type_of_publisher',
            field=models.CharField(choices=[('National', 'National'), ('International', 'International')], max_length=30),
        ),
        migrations.AlterField(
            model_name='journal',
            name='Collaboration',
            field=models.CharField(choices=[('National', 'National'), ('International', 'International'), ('Internal', 'Internal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='journal',
            name='Impact_factor',
            field=models.FloatField(null=True),
        ),
    ]
