# Generated by Django 4.0.5 on 2022-07-08 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_book_chapter_collaboration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_chapter',
            old_name='TYpe_of_publisher',
            new_name='Type_of_publisher',
        ),
    ]
