# Generated by Django 4.0.5 on 2022-07-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_journal_doi_alter_journal_impact_factor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='DOI',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
