# Generated by Django 4.0.5 on 2022-08-02 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_conference_doi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_chapter',
            name='DOI',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='book_chapter',
            name='Emp_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.personal'),
        ),
        migrations.AlterField(
            model_name='book_chapter',
            name='Funder_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Enter Funder name if type is "Open" '),
        ),
        migrations.AlterField(
            model_name='book_chapter',
            name='Issue_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book_chapter',
            name='Vol_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book_editor',
            name='DOI',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='book_editor',
            name='Emp_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.personal'),
        ),
        migrations.AlterField(
            model_name='book_editor',
            name='Funder_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Enter if type is "Open" '),
        ),
        migrations.AlterField(
            model_name='book_editor',
            name='Issue_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book_editor',
            name='Vol_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='Emp_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.personal'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='Funder_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Enter Funder name if type of publications is "Open" '),
        ),
        migrations.AlterField(
            model_name='consultancy_project',
            name='Emp_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.personal'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='Emp_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.personal'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='Funder_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Enter Funder name if type is "Open" '),
        ),
        migrations.AlterField(
            model_name='patent',
            name='Emp_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.personal'),
        ),
    ]
