# Generated by Django 4.0.5 on 2022-08-05 10:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_book_chapter_doi_alter_book_chapter_emp_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='consultancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Product development', 'Product development'), ('Research Collaboration', 'Research Collaboration')], max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('funding_status', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5)),
                ('amount_registered', models.IntegerField(blank=True, null=True)),
                ('amount_sanctioned', models.IntegerField(blank=True, null=True)),
                ('invoice_number', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='consultancy_project',
            name='Emp_ID',
        ),
        migrations.RemoveConstraint(
            model_name='conference',
            name='unique_EmpID_title_conference',
        ),
        migrations.RemoveConstraint(
            model_name='journal',
            name='unique_EmpID_title_journal',
        ),
        migrations.RemoveConstraint(
            model_name='patent',
            name='unique_EmpID_PTitle_combination',
        ),
        migrations.RenameField(
            model_name='conference',
            old_name='title',
            new_name='article_title',
        ),
        migrations.RenameField(
            model_name='conference',
            old_name='Collaboration',
            new_name='collaboration',
        ),
        migrations.RenameField(
            model_name='conference',
            old_name='Conference_name',
            new_name='conference_name',
        ),
        migrations.RenameField(
            model_name='conference',
            old_name='DOI',
            new_name='digital_obj_id',
        ),
        migrations.RenameField(
            model_name='conference',
            old_name='Emp_ID',
            new_name='emp_id',
        ),
        migrations.RenameField(
            model_name='conference',
            old_name='Conference_enddate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='conference',
            old_name='Place_of_conference',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='conference',
            old_name='Conference_startdate',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='conference',
            old_name='Type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='title',
            new_name='article_title',
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='Collaboration',
            new_name='collaboration',
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='DOI',
            new_name='digital_obj_id',
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='Emp_ID',
            new_name='emp_id',
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='Impact_factor',
            new_name='impact_factor',
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='Issue_no',
            new_name='issue_no',
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='Journal_name',
            new_name='journal_name',
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='Type_of_publication',
            new_name='type_of_publication',
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='Vol_no',
            new_name='volume_no',
        ),
        migrations.RenameField(
            model_name='patent',
            old_name='no_of_authors_in_patent',
            new_name='no_of_authors',
        ),
        migrations.RenameField(
            model_name='patent',
            old_name='patent_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='patent',
            old_name='Type_of_patent',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='personal',
            old_name='DOB',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='personal',
            old_name='DOJ',
            new_name='date_of_join',
        ),
        migrations.RenameField(
            model_name='personal',
            old_name='Designation',
            new_name='designation',
        ),
        migrations.RenameField(
            model_name='personal',
            old_name='Emp_ID',
            new_name='emp_id',
        ),
        migrations.RenameField(
            model_name='personal',
            old_name='Google_scholar_name',
            new_name='google_scholar',
        ),
        migrations.RenameField(
            model_name='personal',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='personal',
            old_name='ORCID_ID',
            new_name='orcid',
        ),
        migrations.RenameField(
            model_name='personal',
            old_name='Personal_page',
            new_name='personal_page',
        ),
        migrations.RenameField(
            model_name='personal',
            old_name='Researchgate',
            new_name='research_gate',
        ),
        migrations.RenameField(
            model_name='personal',
            old_name='School',
            new_name='school',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='Amount_of_Publication',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='Author_pos',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='Designation',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='Funder_name',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='Indexed_Scopus',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='Support',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='Type_of_publication',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='Amount_of_Publication',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='Author_pos',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='Designation',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='Funder_name',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='Indexing',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='Support',
        ),
        migrations.RemoveField(
            model_name='patent',
            name='Author_pos',
        ),
        migrations.RemoveField(
            model_name='patent',
            name='Emp_ID',
        ),
        migrations.RemoveField(
            model_name='patent',
            name='patent_created_date',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='Gender',
        ),
        migrations.AddField(
            model_name='conference',
            name='amount_of_publication',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='conducting',
            field=models.CharField(choices=[('Conducting', 'Conducting'), ('Attending', 'Attending')], default='Attending', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conference',
            name='funder_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='indexing',
            field=models.CharField(choices=[('SCI', 'SCI'), ('SCIE', 'SCIE'), ('SCOPUS', 'SCOPUS'), ('Springer', 'Springer')], default='SCI', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conference',
            name='published_as',
            field=models.CharField(choices=[('Research Paper', 'Research Paper')], default='Research Paper', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conference',
            name='support',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='type_of_publication',
            field=models.CharField(choices=[('Subscription', 'Subscription')], default='Subscription', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journal',
            name='amount_of_publication',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='funder_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='indexing',
            field=models.CharField(choices=[('SCI', 'SCI'), ('SCIE', 'SCIE'), ('SCOPUS', 'SCOPUS'), ('Springer', 'Springer')], default='SCI', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journal',
            name='support',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='patent',
            name='emp_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.personal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patent',
            name='filed_date',
            field=models.DateField(default=datetime.datetime(1970, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='patent',
            name='granted_date',
            field=models.DateField(default=datetime.datetime(1970, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='patent',
            name='published_date',
            field=models.DateField(default=datetime.datetime(1970, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='personal',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Prefer not to say', 'Prefer not to say')], default='Male', max_length=20),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='conference',
            constraint=models.UniqueConstraint(fields=('emp_id', 'article_title'), name='unique-emp_id-article_title-conference'),
        ),
        migrations.AddConstraint(
            model_name='journal',
            constraint=models.UniqueConstraint(fields=('emp_id', 'article_title'), name='unique-emp_id-article_title-journal'),
        ),
        migrations.AddConstraint(
            model_name='patent',
            constraint=models.UniqueConstraint(fields=('emp_id', 'patent_title'), name='unique-emp_id-patent_title-patent'),
        ),
        migrations.DeleteModel(
            name='consultancy_project',
        ),
        migrations.AddField(
            model_name='consultancy',
            name='emp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.personal'),
        ),
        migrations.AddConstraint(
            model_name='consultancy',
            constraint=models.UniqueConstraint(fields=('emp_id', 'company_name'), name='unique-emp_id-company_name-consultancy'),
        ),
    ]
