openapi: 3.0.1
info:
  title: CSGT Progress Tracker
  description: "API for the CSGT faculty and research publication tracker. "
  contact:
    email: anirudh.cp2020@vitstudent.ac.in
  version: 0.2.0
externalDocs:
  description: Informal Requirements
  url: https://github.com/anirudh-cp/CSGT-Progress-Track/blob/13761c305e3914dc15496721d6ade1bf0ec1aff1/Dash_SRS.pdf
servers:
  - url: http://127.0.0.1:5000/


tags:
  - name: Faculty
    description: Personal profile page for a faculty.
  - name: Publications
    description: Publications in various mediums.

components:
  schemas:
    Faculty:
      required: [EmpID]
      type: object
      properties:
        EmpID:
          type: string
        Name:
          type: string
        Designation:
          type: string
    Publication:
      type: object
      properties:
        Title:
          type: integer
        Type:
          type: string
        Authors:
          type: object
          properties:
            Name:
              type: string
            Designation:
              type: string


paths:
  /faculty/{EmpID}:
    parameters:
      - name: EmpID
        in: path
        description: Employee ID
        required: true
        schema:
          type: integer
          format: int64
    get:
      summary: View personal account details.
      responses:
        "200":
          description: Faculty details returned successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Faculty"
        "400":
          description: Bad request.
      tags:
        - Faculty

    delete:
      summary: Delete given faculty details.
      responses:
        "200":
          description: Faculty details deleted successfully.
        "400":
          description: Bad request.
      tags:
        - Faculty

  /faculty/{EmpID}/edit:
    parameters:
      - name: EmpID
        in: path
        description: Employee ID
        required: true
        schema:
          type: integer
          format: int64
    put:
      summary: Edit/Add personal information of faculty.
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Faculty"
      responses:
        "200":
          description: Addition is successful.
        "201":
          description: Edit is successful.
        "400":
          description: Bad request.
      tags:
        - Faculty

  /faculty:
    get:
      summary: View all faculty account details
      responses:
        "200":
          description: Faculty details returned successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Faculty"
      tags:
        - Faculty


  /publications/{EmpID}:
    get:
      summary: Filter and View the publications for given faculty.
      description: ""
      parameters:
      - name: EmpID
        in: path
        description: Employee ID
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                Type:
                  type: string
                startDate:
                  type: string
                endDate:
                  type: string
      responses:
        '200':
          description: Records returned successfully.
        "400":
          description: Bad request.
      tags:
        - Publications

  /publications/{EmpID}/edit:
    put:
      summary: Edit/Add publications for given faculty.
      parameters:
      - name: EmpID
        in: path
        description: Employee ID
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Publication"
      responses:
        '200':
          description: Publication added successfully.
        "201":
          description: Publication edited successfully.
        "400":
          description: Bad request.
      tags:
        - Publications
  
  
  /publications:
    get:
      summary: To generate report for all faculties.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                Type:
                  type: string
                startDate:
                  type: string
                endDate:
                  type: string
      responses:
        '200':
          description: Records returned successfully.
      tags:
        - Publications
