# Generated by Django 4.0.5 on 2022-09-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_event_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='sponspored',
            new_name='sponsored',
        ),
        migrations.AddField(
            model_name='book',
            name='upload_link',
            field=models.URLField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='upload_link',
            field=models.URLField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='consultancy',
            name='upload_link',
            field=models.URLField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='upload_link',
            field=models.URLField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='industrial_interaction',
            name='upload_link',
            field=models.URLField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='upload_link',
            field=models.URLField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='patent',
            name='upload_link',
            field=models.URLField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='upload_link',
            field=models.URLField(blank=True, max_length=350, null=True),
        ),
    ]
